<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Carbon.Azure.Facial</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FaceAiSharp.Bundle" Version="0.6.35" />
      <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.26.0" />
    </ItemGroup>

</Project>
